name: Build e Deploy no Kubernetes GKE

on:
  push:
    branches:
    - staging

# Variáveis de ambiente setadas no secrets do Github
env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  GKE_CLUSTER: ${{ secrets.CLUSTER_NAME }}
  GKE_ZONE: ${{ secrets.CLUSTER_ZONE }}
  IMAGE: evandromorini/devops-app-a

jobs:
  # Login no Docker Hub
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Setup do google SDK (gcloud)
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_email: ${{ secrets.SA_EMAIL }}
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

    - run: |-
        gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE" --project $PROJECT_ID

    # Build da imagem
    - name: Build
      run: |-
        docker build \
          --tag "evandromorini/devops-app-a" .

    # Push da imagem para o Dockerhub
    - name: Publish
      run: |-
        docker push "evandromorini/devops-app-a"

    # Incluindo a tag da branch de staging
    - name: Tag Staging
      run: |-
        docker tag evandromorini/devops-app-a evandromorini/devops-app-a:staging
        docker push evandromorini/devops-app-a:staging

    # Instalando Kustomize
    - name: Set up Kustomize
      run: |-
        curl -o kustomize --location https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize

    # Deploy da imagem no Kubernetes
    - name: Deploy
      run: |-
        cd k8s/overlays/staging
        ../../../kustomize edit set image evandromorini/devops-app-a=evandromorini/devops-app-a:staging
        ../../../kustomize build . | kubectl apply -f -
        kubectl -n staging rollout status deployment/$IMAGE
