apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-app-a
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: devops-app-a
      containers:
      - name: devops-app-a
        resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            cpu: "100m"
            memory: "256Mi"